/* 1. */
select MASP,TENSP 
FROM SANPHAM
WHERE NUOCSX = 'TRUNG QUOC'

/* 2. */

SELECT MASP, TENSP
FROM SANPHAM
WHERE DVT IN('cay','quyen')

/* 3. */

SELECT MASP,TENSP
FROM SANPHAM
WHERE MASP LIKE 'B%01'

/* 4. */

SELECT MASP,TENSP
FROM SANPHAM
WHERE (NUOCSX = 'TRUNG QUOC') AND (GIA BETWEEN 30000 AND 40000)

/* 5. */

SELECT MASP,TENSP
FROM SANPHAM
WHERE (NUOCSX IN ('THAI LAN','TRUNG QUOC')) AND (GIA BETWEEN 30000 AND 40000)

/* 6. */

SELECT SOHD,TRIGIA
FROM HOADON
WHERE NGHD IN  ('1/1/2007','1/2/2007')

/* 7. */

SELECT SOHD, TRIGIA
FROM HOADON
WHERE (YEAR(NGHD) = 2007 AND MONTH(NGHD) = 1)
ORDER BY NGHD ASC,TRIGIA DESC

/* 8. */

SELECT KH.MAKH,HOTEN
FROM KHACHHANG KH,HOADON HD
WHERE (KH.MAKH = HD.MAKH) AND NGHD = '1/1/2007'

/* 9. */

SELECT SOHD,TRIGIA
FROM HOADON HD,NHANVIEN NV
WHERE (HD.MANV = NV.MANV) AND (NV.HOTEN IN('NGUYEN VAN B')) AND HD.NGHD = '10/28/2006'

/* 10 */

SELECT MASP, TENSP
FROM SANPHAM SP
WHERE EXISTS (SELECT 1 
			FROM CTHD CT
			WHERE SP.MASP = CT.MASP AND EXISTS(SELECT 1
									FROM KHACHHANG KH,HOADON HD
										WHERE HD.MAKH = KH.MAKH AND HD.SOHD = CT.SOHD AND YEAR(NGHD) = 2006 AND MONTH(NGHD) = 10 AND KH.HOTEN = 'NGUYEN VAN A'))


/* 11. */
SELECT  * 
FROM CTHD
WHERE MASP IN ('BB01','BB02')

/* 12 */
SELECT CT1.SOHD
FROM CTHD CT1
WHERE (CT1.SL BETWEEN 10 AND 20) AND CT1.MASP = 'BB01'

UNION

SELECT CT2.SOHD
FROM CTHD CT2
WHERE (CT2.SL BETWEEN 10 AND 20) AND CT2.MASP = 'B002'

/* 13. */
SELECT CT1.SOHD
FROM CTHD CT1
WHERE (CT1.SL BETWEEN 10 AND 20) AND CT1.MASP = 'BB01'

INTERSECT

SELECT CT2.SOHD
FROM CTHD CT2
WHERE (CT2.SL BETWEEN 10 AND 20) AND CT2.MASP = 'B002'

/* 14. */

SELECT SP.TENSP, SP.MASP
FROM SANPHAM SP
WHERE SP.NUOCSX = 'TRUNG QUOC' OR SP.MASP IN(SELECT CT.MASP
									FROM CTHD CT
									WHERE CT.SOHD IN(SELECT HD.SOHD
														FROM HOADON HD
														WHERE HD.NGHD = '1/1/2007' ))
/* 15. */

SELECT SP.MASP, SP.TENSP
FROM SANPHAM SP
WHERE NOT EXISTS (SELECT *
				FROM CTHD CT
				WHERE CT.MASP = SP.MASP)
/* 16. */

SELECT SP.MASP, SP.TENSP
FROM SANPHAM SP
WHERE NOT EXISTS (SELECT 1
				FROM CTHD CT
				WHERE CT.MASP = SP.MASP AND EXISTS (SELECT 1
													FROM HOADON HD	
													WHERE HD.SOHD = CT.SOHD AND YEAR(HD.NGHD) = 2006))

/* 17. */

SELECT SP.MASP, SP.TENSP
FROM SANPHAM SP
WHERE SP.NUOCSX = 'TRUNG QUOC' AND NOT EXISTS (SELECT 1
												FROM CTHD CT
												WHERE CT.MASP = SP.MASP AND EXISTS (SELECT 1
																					FROM HOADON HD	
																					WHERE HD.SOHD = CT.SOHD AND YEAR(HD.NGHD) = 2006))
/* 18. */

/* TEST. */

